application: story-log
version: 1-1
runtime: python
api_version: 1

default_expiration: "30d"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.gitignore$
- ^(.*/)?.config\.rb$
- ^(.*/)?.README$
- ^(.*/)?.*/.git/.*
- ^(.*/)?.*/src/.*
- ^(.*/)?.*/story_b/.*

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /.*
  script: storylog.py
